name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
          cat .env
          ls -al

      - name: Generate static site
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run predeploy

      - name: Init repository an push to GitHub Pages
        run: |
          cd ./build
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build
